[package]
name = "karrot_exchange"
version = "0.1.1"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"

[dependencies]
starknet = "2.3.1"

[tool.snforge]
# exit_first = true
